### ISSUE TITLE
2 extra/bogus Zones generated

### ISSUE THREAD

**Issue by taw123** [foxy82/hacs-onkyo-repository#3]
My Onkyo has only 2 zones but like the "offical" Integration it seems this integration has unfortunately generated 4 zones.

I am left with same problem unfortunately. I filed my feature request for the orignal integration ( [that](https://github.com/home-assistant/core/issues/75221) spawned a discussion/creation of this integration year ago)one can't delete or modify devices in this integration (outside the YAML platform definition) I can't delete these bogus zones that are cluttering the  default UI pages.

Any suggestions on how to purge these bogus zones/entities. It can't be done from the configuration override (which I am using to add the model number as an attribute to this integration.

My questions where is the device definition made that defines the number of zones? This dosen't SEEM to be created dynamically from the platform YAML as mine only has 2 zones defined by 4 entities/zones created 

```
  - platform: onkyo_async
    host: 192.168.42.86
    name: "Onkyo AVR Living Room"
    max_volume: 78
    sources:
      cd: "Amazon"
      fm: "fm"
      net: "net"
      video1: "DirectTV"
      video2: "AppleTV"
      video3: "Games"
      video4: "Aux"
      video6: "MacMini"
    zones:
      zone2:
        name: Onkyo Dining Room zone
        max_volume: 78

```
Thanks!
